#!/usr/bin/env python


import paramiko

CLI_command_list = [("BMC network status","net int show"),("Checking cluster status","cluster show"),("Checking sp show","sp show")]
p= paramiko.SSHClient()
cred = open("cred.csv","r")


def dump_logfile(fileid,buf):
    fileid.write(buf)

def run_basic_commands(Command,fileid,timeout=150):
    command = Command[1]
    stdin,stdout,stderr = p.exec_command(command)
    opt = stdout.readlines()
    opt = "".join(opt)
    print(opt)
    dump_logfile(fileid,opt)

for i in cred.readlines():
    line = i.strip()
    ls = line.split(",")
    print ls
    p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    p.connect("%s"%ls[0], port=22, username = "%s"%ls[1],password="%s"%ls[2])
    #Open a file for logging all infomation
    logfile = open("bmc_sanitytest.txt","a+")
    for command in CLI_command_list:
        run_basic_commands(command,logfile)

    logfile.close()
cred.close()
